"""Prepare files for image creation.

Copyright (c) 2024 to present Mitja Maximilian Zdouc, PhD and individual contributors.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
"""

import json
import logging
from pathlib import Path
from typing import Self

from alphafetcher import AlphaFetcher
from pydantic import BaseModel, DirectoryPath, FilePath

logger = logging.getLogger("prep_data")


class ImageManager(BaseModel):
    """Manages the download of PDB files from AlphaFold and creating of protein images.

    Images are generated by a separate bash script "run_pymol.sh" due to issues in running PyMol as subprocess

    Attributes:
        uniprot_acc: a list of uniprot accession IDs for download
        src: a Path towards the mite json file directory
        target_download: a Path towards the PDB file target (storage) directory
        target_img: a Path towards the image file target (storage) directory
    """

    uniprot_acc: list = []
    src: FilePath = Path(__file__).parent.parent.joinpath("data/data/")
    target_download: DirectoryPath = Path(__file__).parent.parent.joinpath("data/pdb/")
    target_img: DirectoryPath = Path(__file__).parent.parent.joinpath("data/img/")

    def run(self: Self) -> None:
        """Class entry point to run methods"""
        logger.info("ImageManager: Started")

        if self.target_download.exists():
            logger.warning(
                f"ImageManager: Directory {self.target_download} already exists - skip file preparation"
            )
            return

        self.collect_uniprot_acc()
        self.download_pdbs()

        logger.info("ImageManager: Completed")

    def collect_uniprot_acc(self: Self) -> None:
        """Collect uniprot accession IDs from the metadata file"""
        for mite_file in self.src.iterdir():
            with open(mite_file) as file_in:
                data = json.load(file_in)
            if data["status"] == "active":
                if acc := data["enzyme"].get("databaseIds", {}).get("uniprot", None):
                    self.uniprot_acc.append(acc)

    def download_pdbs(self: Self) -> None:
        """Download PDB-files from AlphaFold using the uniprot acc ids"""
        self.target_download.mkdir(parents=True, exist_ok=True)
        fetcher = AlphaFetcher(base_savedir=str(self.target_download))
        fetcher.add_proteins(proteins=self.uniprot_acc)
        fetcher.download_all_files(pdb=True, multithread=True, workers=4)

        try:
            for infile in self.target_download.joinpath("pdb_files").iterdir():
                infile.rename(self.target_download / infile.name)
            self.target_download.joinpath("pdb_files").rmdir()
        except FileNotFoundError("No PDB files downloaded from AlphaFoldDB - SKIP"):
            return
